# Generated by Django 4.1.5 on 2023-01-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('mem_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('mem_name', models.CharField(max_length=8)),
                ('mem_point', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
