# Generated by Django 4.1.5 on 2023-01-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_channel_2_channel_3_channel_4'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel_1',
            name='ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='channel_2',
            name='ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='channel_3',
            name='ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='channel_4',
            name='ready',
            field=models.BooleanField(default=False),
        ),
    ]
