# Generated by Django 4.1.5 on 2023-01-27 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_channel_1_ready_channel_2_ready_channel_3_ready_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel_1',
            name='finish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='channel_2',
            name='finish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='channel_3',
            name='finish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='channel_4',
            name='finish',
            field=models.BooleanField(default=False),
        ),
    ]
