# Generated by Django 4.1.5 on 2023-01-27 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_channel_1_finish_channel_2_finish_channel_3_finish_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel_1',
            old_name='finish',
            new_name='labeling',
        ),
        migrations.RenameField(
            model_name='channel_2',
            old_name='finish',
            new_name='labeling',
        ),
        migrations.RenameField(
            model_name='channel_3',
            old_name='finish',
            new_name='labeling',
        ),
        migrations.RenameField(
            model_name='channel_4',
            old_name='finish',
            new_name='labeling',
        ),
    ]
