# Generated by Django 3.2.16 on 2023-02-22 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_remove_channel_1_labeling_remove_channel_2_labeling_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='mem_exp',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
