# Generated by Django 3.2.16 on 2023-02-23 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_member_mem_exp'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='mem_level',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
