# Generated by Django 3.2.16 on 2023-04-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_member_mem_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entries_per_emotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(max_length=8)),
                ('E1_flag', models.BooleanField(default=False)),
                ('E2_flag', models.BooleanField(default=False)),
                ('E3_flag', models.BooleanField(default=False)),
                ('E1_teamid', models.CharField(max_length=8, null=True)),
                ('E2_teamid', models.CharField(max_length=8, null=True)),
                ('E3_teamid', models.CharField(max_length=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entries_per_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion_id', models.CharField(max_length=8)),
                ('E1_labeler', models.CharField(max_length=8, null=True)),
                ('E2_labeler', models.CharField(max_length=8, null=True)),
                ('E3_labeler', models.CharField(max_length=8, null=True)),
                ('E1_implicit', models.CharField(max_length=10, null=True)),
                ('E2_implicit', models.CharField(max_length=10, null=True)),
                ('E3_implicit', models.CharField(max_length=10, null=True)),
                ('E1_time', models.DateTimeField(auto_now_add=True)),
                ('E2_time', models.DateTimeField(auto_now_add=True)),
                ('E3_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='team_id',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='mem_name',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
