# Generated by Django 3.2.16 on 2023-04-20 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20230420_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='entries_per_image',
            name='image_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.entries_per_emotion'),
        ),
        migrations.AlterField(
            model_name='entries_per_emotion',
            name='image_id',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
