# Generated by Django 3.2.16 on 2023-04-21 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_auto_20230420_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(blank=True, max_length=8)),
                ('emotion_id', models.CharField(blank=True, max_length=8)),
                ('E1_flag', models.BooleanField(default=False)),
                ('E2_flag', models.BooleanField(default=False)),
                ('E3_flag', models.BooleanField(default=False)),
                ('E1_teamid', models.CharField(blank=True, max_length=8)),
                ('E2_teamid', models.CharField(blank=True, max_length=8)),
                ('E3_teamid', models.CharField(blank=True, max_length=8)),
                ('E1_labeler', models.CharField(blank=True, max_length=8)),
                ('E2_labeler', models.CharField(blank=True, max_length=8)),
                ('E3_labeler', models.CharField(blank=True, max_length=8)),
                ('E1_implicit', models.CharField(blank=True, max_length=10)),
                ('E2_implicit', models.CharField(blank=True, max_length=10)),
                ('E3_implicit', models.CharField(blank=True, max_length=10)),
                ('E1_time', models.DateTimeField(auto_now_add=True)),
                ('E2_time', models.DateTimeField(auto_now_add=True)),
                ('E3_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='entries_per_image',
            name='image_id',
        ),
        migrations.DeleteModel(
            name='Entries_per_emotion',
        ),
        migrations.DeleteModel(
            name='Entries_per_image',
        ),
        migrations.AddIndex(
            model_name='entries',
            index=models.Index(fields=['image_id'], name='game_entrie_image_i_7b9e63_idx'),
        ),
    ]
