# Generated by Django 3.2.16 on 2023-04-21 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_auto_20230421_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='entries',
            name='E1_labeling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entries',
            name='E2_labeling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entries',
            name='E3_labeling',
            field=models.BooleanField(default=False),
        ),
    ]
