# Generated by Django 3.2.16 on 2023-04-21 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_auto_20230421_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entries',
            name='E1_labeling',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='entries',
            name='E1_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='entries',
            name='E2_labeling',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='entries',
            name='E2_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='entries',
            name='E3_labeling',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='entries',
            name='E3_time',
            field=models.DateTimeField(null=True),
        ),
    ]
