# Generated by Django 3.2.16 on 2023-05-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_auto_20230421_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel_1',
            name='user',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
