# Generated by Django 3.2.16 on 2023-05-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_alter_channel_1_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel_2',
            name='user',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='channel_3',
            name='user',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='channel_4',
            name='user',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='mem_name',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
