# Generated by Django 3.2.16 on 2023-05-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_auto_20230519_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entries',
            name='E1_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entries',
            name='E2_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entries',
            name='E3_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
